---
# RENAME this file to secrets.yml

development:
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DB_KEY: pFrP9v4qQNRvpEeLl4RL0s8C3pmMyOKTYrjHhb2rq4g=
  APP_URL: http://127.0.0.1:9292
  DATABASE_URL: xxx
  SENDGRID_API_KEY: xxx
  SENDGRID_FROM_EMAIL: xxx
  SECURE_SCHEME: HTTP


test:
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DB_KEY: pFrP9v4qQNRvpEeLl4RL0s8C3pmMyOKTYrjHhb2rq4g=
  APP_URL: http://127.0.0.1:9292
  DATABASE_URL: xxx
  SENDGRID_API_KEY: xxx
  SENDGRID_FROM_EMAIL: xxx
  SECURE_SCHEME: HTTP

production:
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  DATABASE_URL: <set to production DB>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP
